#include <stdio.h>

int main()
{
    FILE *fptr;
    char ch[100] = "#include <stdio.h>\nint main()\n{\n    printf(\"Hello World\");\nreturn 0;};";
    fptr = fopen("Genarated.txt", "w");
    fprintf(fptr, "%s", ch);
    fprintf(fptr, "// This file is generated by the program\n", ch);
    fclose(fptr);
    return 0;
}
